# Generated by Django 5.0 on 2023-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='travel_images/')),
            ],
        ),
    ]
