# Generated by Django 5.0 on 2023-12-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
