# Generated by Django 5.0 on 2023-12-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0009_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='card_number',
            new_name='cardnumber',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='expiration',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
