# Generated by Django 5.0 on 2023-12-31 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0010_rename_card_number_reservation_cardnumber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
