# Generated by Django 5.0 on 2024-01-03 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0012_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='travel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.travel'),
            preserve_default=False,
        ),
    ]
