# Generated by Django 3.2.12 on 2024-01-22 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0014_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='my_user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
