# Generated by Django 3.2.12 on 2024-01-22 15:16

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0015_auto_20240122_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cardnumber',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cvv',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='expiration',
            field=models.DateField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=timezone.now),
        ),
    ]
