# Generated by Django 3.2.12 on 2024-01-22 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0016_auto_20240122_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
