# Generated by Django 3.2.12 on 2024-01-22 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0017_auto_20240122_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 22)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration',
            field=models.DateField(default=datetime.date(2024, 1, 22)),
        ),
    ]
