# Generated by Django 3.2.12 on 2024-01-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0019_auto_20240122_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
