# Generated by Django 3.2.12 on 2024-01-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0020_auto_20240122_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
