# Generated by Django 3.2.12 on 2024-01-23 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0022_auto_20240122_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='mydate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
